Num1 = input("Enter first number: ")
Num2 = input("Enter second number: ")
Sum = float(Num1) + float(Num2)
print("The sum is:", Sum)
diff = float(Num1) - float(Num2)
print("The difference is:", diff)
multiply = float(Num1) * float(Num2)
print("The multiplication is:", multiply)
divide = float(Num1) / float(Num2)
print("The division is:", divide)